# =============================================================
# http.conf — Redirection HTTP → HTTPS + challenge ACME
# =============================================================

server {
    listen       80;
    listen  [::]:80;
    server_name  sunushop.sn www.sunushop.sn;

    # Challenge Let's Encrypt (certbot --webroot)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        try_files $uri =404;
    }

    # Tout le reste → HTTPS www
    location / {
        return 301 https://www.sunushop.sn$request_uri;
    }
}
